---
keys:
  # Personal
  - &admin_johnny age1thw8surng7e2hxws052fdje0nfftmh42e523tcrts7ltla4nmenqatj7sz
  - &admin_jwalker age1qx4hqya7q5y43dzh5fyfhu4yn0m508mrf3rd4tfxytaclwvpfadqgnd2ls
  # Hosts
  - &host_m3800 age1a5glegke4qggmu4ah08f53s4trhh6sc59vpx2z6kqvuchwdzs4eqa56er3
  - &host_petey age10mddgy5g7ws2gdakd90hn8sswctzwfjmr9xae55dw95zq24kyqdqma8uzh
creation_rules:
  - path_regex: hosts/.*/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_johnny
      - *admin_jwalker

  - path_regex: home/.*/secrets\.yaml$
    key_groups:
    - age:
      - *admin_johnny
      - *admin_jwalker

  - path_regex: hosts/common/.*/secrets\.ya?ml$
    key_groups:
    - age:
      - *admin_johnny
      - *admin_jwalker
      - *host_m3800
      - *host_petey
